name: Deploy to Render

on:
  push:
    branches:
      - main  # Runs when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t zekajj/ueb20-22-gr9 .
          docker tag zekajj/ueb20-22-gr9 zekajj/ueb20-22-gr9:latest
          docker push zekajj/ueb20-22-gr9:latest

      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.DEPLOY_HOOK }}"

